### ISSUE TITLE
Currency options (GBP)

### ISSUE THREAD

**Issue by FuturamaPhill** [boralyl/steam-wishlist#27]
**Is your feature request related to a problem? Please describe.**
Not a problem but would be nice to be able to change currency to anything of our choosing such as GBP.

**Describe the solution you'd like**
Not sure how it would be implemented but maybe a configuration option to select currency or location.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by boralyl** [comment]
@FuturamaPhill Currently the component doesn't know what the currency is, it's simply stored as floats like the following (you can view this in HA's developer tools if you search for one of these entities): 

```yaml
-  normal_price: 19.98
   percent_off: 40
   sale_price: 11.99
```

There doesn't appear to be an easy way to know what type of currency that value is based on the json data from your wish list.  So it would be hard to know what the current currency is in order to convert it to another currency.

**Comment by Super1337Boy** [comment]
There is no need to convert currency. I get the values in my local currency automatically. It would just be nice to at least be able to hide the dollar sign, and ideally also add the correct currency type. In my case that could look something like: 

199 kr

This is what it looks like now:
![wishlist](https://github.com/user-attachments/assets/12509623-d15a-4062-a27e-a49cf2c4caf2)

**Comment by boralyl** [comment]
Oh!  That makes sense, yeah this integration just gets the data, it doesn't display it at all.  That's handled by a separate card.
